### ISSUE TITLE
Store submission's new location

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/submission-processor#15]
Once the processor is done moving the file around, the final location of the submission (whether it is infected or not does not matter, only the final location does) will be stored in the submission itself.

Make the submission API call to update the submission's url.

**Comment by callmekatootie** [comment]
Update the tests as needed too

**Comment by callmekatootie** [comment]
Assigning this one to @sharathkumaranbu . Tagging him in case we make any updates here

**Comment by callmekatootie** [comment]
@BadalZ @cwdcwd Any idea how to generate m2m token to get `update:submission` scope, in order for processor to call submission api to update url of submission?

**Comment by sharathkumaranbu** [comment]
@callmekatootie @cwdcwd @BadalZ In order to update the URL of the submission using Submission API, We would need a m2m token with `update:submission` scope.

Problems I see here is

1. M2M token is generated by Auth0, hence only Auth0 can validate the token. Else, if we know the JWT key used by Auth0 to generate the token, Submission API can validate the token using the library `tc-core-library.jwt.jwtAuthenticator`

2. But I am not sure if sharing JWT key between applications is really recommended. 

3. If keys should not be shared, then there should be a function using Auth0 to validate the token and return the decrypted token. There is no such function exists in the Authentication library.

Note: jwtAuthenticator in tc-core-library-js can be used only when we know the `AUTH_SECRET` used for token generation, else it won't work

**Comment by cwdcwd** [comment]
- `update:submission` should be in the scopes for the `maE2maBSv9fRVHjSlC31LFZSq6VhhZqC` M2M clientId 
- we should have an `AUTH_SECRET` env var for the signing secret to enable validation

This same validation exists on the submission API itself

**Comment by sharathkumaranbu** [comment]
@cwdcwd Is it ideal to share AUTH_SECRET between many applications?

**Comment by cwdcwd** [comment]
it's not shared at run time. it's set in the env vars for the services themselves so it's isolated to the application's environment. but yes, this is the only way to validate those sorts of signatures. Otherwise we have to switch to a PKI-based signature which I don't think we're ready for

**Comment by sharathkumaranbu** [comment]
@cwdcwd Could you share the Auth0 credentials for M2M Client Id `maE2maBSv9fRVHjSlC31LFZSq6VhhZqC` and AUTH_SECRET for verifying the signature via Email or Slack (Username: Sharathkumar92)
